#!/usr/bin/env bash
#Displaying Best School 10 times using the until loop
i=0

until false; do
    echo "Best School"
    ((i++))
    if [[ $i -lt 10 ]]; then 
        continue
    else
        break
    fi
done
             